### ISSUE TITLE
hid_set_nonblocking() is not effective

### ISSUE THREAD

**Issue by wuuhii** [libusb/hidapi#113]
Hello world， maybe there is a bug in the version 0.9.0:
the function (int  HID_API_EXPORT HID_API_CALL hid_set_nonblocking(hid_device *dev, int nonblock))is not effective.

**Comment by wuuhii** [comment]
The platform is Windows

**Comment by Youw** [comment]
Would be nice if you provide more details:
- what kind of device you're using;
- steps to reproduce/sample of your code;
- what exactly do you observe/actual result;
- what are your exact expectations, based on your implementation;

**Comment by wuuhii** [comment]
I am sorry，I used it the wrong way.
