### ISSUE TITLE
can't communicate with device Freestyle libre glucometer 

### ISSUE THREAD

**Issue by Chakib-Temal** [libusb/hidapi#122]
Hi , i use yours library to communicate with an HID device (Freestyle libre abbot) 

i used the example code, the device is detectable, here is the logout 

`Device Found
  type: 1a61 3650
  path: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/PRT1@14100000/ADC Reader@14100000/Hid Interface@0/IOUSBHostHIDDevice@14100000,0
  serial_number: 
  Manufacturer: Abbott Diabetes Care
  Product:      ADC Reader
  Release:      100
  Interface:    0

hid device opened 
Manufacturer String: A
Product String: A
Serial Number String: (0) 
Indexed String 1: `

is it normal ? why the manufacturer change ? 

the execution of the code is blocked in this line :

`// Toggle LED (cmd 0x80). The first byte is the report number (0x0).
    buf[0] = 0x80;
    //buf[1] = 0x80;
    res = hid_write(handle, buf, 64); // HERE

    // Request state (cmd 0x81). The first byte is the report number (0x0).
    buf[0] = 0x81;
    //buf[1] = 0x81;
    res = hid_write(handle, buf, 64);`

i don't have any answer from the device ! 

i know that the first frame to initializ the communication is a buffer [64] , with buffer[0] = 0x04
i already do it in java without initialing set/get repport 

here is somme documentation that i can't really understand about settings usb freestyle libre
`These devices appears on the USB bus as a HID device. The communication between the software and the device happens through HID Set Report/Get Report interfaces, in a way that is compatible with the Linux hidraw interface.

In particular the packets are sent on the Control endpoint, as Class Interface messages (bRequestType = 0x21, bRequest = 0x09, wValue = 0x0200, wIndex = 0x0000), and received on the interrupt endpoint (0x81). Report numbers are not used.

The “reports” are not following the HID standard. They are of a fixed 64-bytes size, even if most of the commands themselves are shorter. Replies can span multiple inbound reports.`

did you have any idea please ? thank's

**Comment by mcuee** [comment]
You may want to read Ch7 of the HID specification.
