### ISSUE TITLE
macOS: Bluetooth HID devices have the same path

### ISSUE THREAD

**Issue by erikmwerner** [libusb/hidapi#127]
hidapi returns the same path IOService:/IOResources/IOBluetoothHCIController/AppleBroadcomBluetoothHostController/IOBluetoothDevice/IOBluetoothL2CAPChannel/IOBluetoothHIDDriver

For every Bluetooth HID device connected. Tested with:
Nintendo Switch JoyCon (L)
Nintendo Switch JoyCon (R)
Nintendo Switch ProController
Microsoft Bluetooth Mouse 5000

(all devices have unique product IDs and serial numbers)

As a result, hid_open(vendor_id, product_id, serial_number) does not open the correct device if there is more than one bluetooth device paired since it eventually calls hid_open_path, and all the paths are identical. It looks like it will always try to open the device that was paired first.

I can open the correct device if I store a copy of the IOHIDDeviceRef in hid_device_info and create an IOHIDDevice with the reference rather than looking up the IORegistry entry from the path.

This is on a MacBookPro11,1 running macOS 10.14.6.

**Comment by Youw** [comment]
It looks like the same issue as https://github.com/signal11/hidapi/issues/379

@erikmwerner try if you can apply https://github.com/flirc/hidapi/commit/8d251c3854c3b1877509ab07a623dafc8e803db5 locally and check if it fixes your issue

It seems like patch by @flirc preserves backward compatibility and adds stability/reliability to `hid_open_path` on macOS, but before submitting it to master, I'd love to head some alternative opinions

**Comment by erikmwerner** [comment]
I can confirm that https://github.com/flirc/hidapi/commit/8d251c3854c3b1877509ab07a623dafc8e803db5 fixes the issue for me. Thanks for pointing me in the right direction.

As an alternative, the solution that I described above also fixed the issue. I uploaded it at https://github.com/erikmwerner/hidapi/commit/1d65b88edb3c40653c1f06f32f0ffeff4a175f11

**Comment by Youw** [comment]
Thanks.

Yes, it seems like erikmwerner@1d65b88 would fix your issue, but having same API for all 4 backends is more a bit more preferable to me.

@jdk do you think you could prepare a PR to master with flirc/hidapi@8d251c3 ?

**Comment by mcuee** [comment]
So #127 and #236 have the same fix in https://github.com/flirc/hidapi/commit/8d251c3 but that fix needs some modification to be accepted, right?

**Comment by Youw** [comment]
Right. flirc/hidapi@8d251c3 has a leak in the implementation, that's for sure, but the idea is fine.
