### ISSUE TITLE
hidapi license - closed source project

### ISSUE THREAD

**Issue by Stoccarda** [libusb/hidapi#132]
Hi,
hidapi may be used in a closed source project (proprietary software). It will be included in the software which is distributed in binary form.
I have seen the three possible licenses for hidapi.

Will it be correct and sufficient for a closed source project to add to the the own copyright notice a paragrph like
 
Part of the code for USB communication is 
Copyright 2009, Alan Ott, Signal 11 Software.
All Rights Reserved.

or what will be the right way (i.e. text) to fullfil the license.
There is another USB device controlled by the software, but it is a HID.

Thanks for clarification !

**Comment by z3ntu** [comment]
Quoting `LICENSE.txt`:

> An author of commercial closed-source software would likely use HIDAPI
under the terms of the BSD-style license or the original HIDAPI license.

You can read those license texts under `LICENSE-bsd.txt` and `LICENSE-orig.txt`. When I doubt it would be best to consult a lawyer.
