### ISSUE TITLE
I am having unresolved external symbol errors. How do i fix it.

### ISSUE THREAD

**Issue by BarisUygun** [libusb/hidapi#157]
I import hidapi.h to my project i can access the functions but i get external symbol errors for all of them. How do i fix this?

**Comment by z3ntu** [comment]
You need to link against hidapi as well.

**Comment by BarisUygun** [comment]
Yeah i tried that Properties -> C/C++ -> general -> additional include directories 
Is this the right way?

**Comment by z3ntu** [comment]
Include != linking

See if https://stackoverflow.com/a/4446085 helps you

**Comment by BarisUygun** [comment]
Thank you i solved it using the link.
