### ISSUE TITLE
Is there a way to send or recieve signals to/from a keyboard

### ISSUE THREAD

**Issue by BarisUygun** [libusb/hidapi#159]
I am triying to light my keyboard caps lock light.

**Comment by Youw** [comment]
There is no way to do it on Windows with hidapi.
Having access to a keyboard is a security concern, so Windows prohibits it.

Take a look at: [SetKeyboardState](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setkeyboardstate)
