### ISSUE TITLE
[Question] How to rumble(forcefeedback) gamepad?

### ISSUE THREAD

**Issue by DuckerMan** [libusb/hidapi#167]
Hi there! There's example how to turn `LED`. But how do I rumble gamepad?

**Comment by Youw** [comment]
1) You have to check with the documentation to your Gamepad. This library is about an API to access HID devices, not about some specific devices protocols.

2) Gamepad likely to be an input device, and there is high chance that Windows/macOS won't let you access it at all with hidapi directly. You might need to access those using some OS specific (input) functions or another input libraries.
