### ISSUE TITLE
Crashing on Catalina 10.14.6 

### ISSUE THREAD

**Issue by hstriepe** [libusb/hidapi#179]
I installed xquartz and fox via brew.
I build the libHID and testgui using the manual method.
I also tried with autotools. Both builds give the same crash.

Xcode is 11.6.

It crashes with the following message:
0   libdyld.dylib                 	0x00007fff688c070a stack_not_16_byte_aligned_error + 0

Truncated dump:
Process:               hidapi-testgui [27993]
Path:                  /Volumes/VOLUME/*/TestGUI.app/Contents/MacOS/hidapi-testgui
Identifier:            us.signal11.hidtestgui
Version:               1.0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           hidapi-testgui [27993]
User ID:               501

Date/Time:             2020-08-01 09:40:52.330 -0700
OS Version:            Mac OS X 10.15.6 (19G73)
Report Version:        12
Anonymous UUID:        EE566D38-972C-A2E4-BB62-7F00D9088722

Sleep/Wake UUID:       6EEB9B98-FBE0-40D9-A44F-7943A39990B5

Time Awake Since Boot: 56000 seconds
Time Since Wake:       2400 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [27993]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdyld.dylib                 	0x00007fff688c070a stack_not_16_byte_aligned_error + 0
1   ???                           	0x00006000034b8870 0 + 105553171548272

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000001438  rbx: 0x000000000000008c  rcx: 0x0000000000000070  rdx: 0x0000000000000001
  rdi: 0x00006000034b8870  rsi: 0x000000000000000c  rbp: 0x00006000034b8870  rsp: 0x00007ffee70b91b8
   r8: 0x0000000000000195   r9: 0x0000000000000070  r10: 0x00007f8cff81e0e8  r11: 0x0000000108d2a030
  r12: 0x0000000000000006  r13: 0x0000000000000070  r14: 0x0000000000000018  r15: 0x0000000000000400
  rip: 0x00007fff688c070a  rfl: 0x0000000000010202  cr2: 0x000000010a003908
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     13

Binary Images:
       0x108b46000 -        0x108b50ffb +us.signal11.hidtestgui (1.0) <D39C0D57-F907-357A-B5AF-86FB580E6B95> /Volumes/VOLUME/*/TestGUI.app/Contents/MacOS/hidapi-testgui
       0x108b5e000 -        0x108d05fff +libFOX-1.6.0.dylib (0) <AEDE64F0-003F-3096-84DB-EDC597603526> /Volumes/VOLUME/*/TestGUI.app/Contents/MacOS/libFOX-1.6.0.dylib
       0x108e15000 -        0x108f20fff +libX11.6.dylib (10) <1BAB7ED3-D9A4-3AAD-9DBA-CCA9C5F54E49> /opt/X11/*/libX11.6.dylib
       0x108f4b000 -        0x108f57fff +libXext.6.dylib (11) <899041F6-4E8D-322E-9A21-03BDB005BD63> /opt/X11/*/libXext.6.dylib
       0x108f63000 -        0x108febfff +libfreetype.6.dylib (19.6) <51ECD8C8-7B61-3A4A-8C22-0E207ACC2383> /opt/X11/*/libfreetype.6.dylib
       0x109008000 -        0x10903bfff +libfontconfig.1.dylib (11.2) <8742C51B-EB57-3D24-ABA1-DE3853A12966> /opt/X11/*/libfontconfig.1.dylib
       0x109054000 -        0x109063fff +libXft.2.dylib (6.2) <AECF147B-E501-3A17-854B-9DF6EAD9741A> /opt/X11/*/libXft.2.dylib
       0x109072000 -        0x109079ff7 +libXcursor.1.dylib (2.2) <7D54773C-F6BF-3ABF-BD44-C7ABA5A8AB6A> /opt/X11/*/libXcursor.1.dylib
       0x109082000 -        0x109088fff +libXrender.1.dylib (5) <5D636930-CDBD-3098-876E-827CF3314F75> /opt/X11/*/libXrender.1.dylib
       0x109094000 -        0x10909bfff +libXrandr.2.dylib (5) <3A827840-3495-37C2-84F0-913EA3F99D52> /opt/X11/*/libXrandr.2.dylib
       0x1090a7000 -        0x1090aafff +libXfixes.3.dylib (5) <4C581BB8-C505-32A0-8D08-11DCDCF6446B> /opt/X11/*/libXfixes.3.dylib
       0x1090b0000 -        0x1090bbff7 +libXi.6.dylib (8) <CFD56DE2-58D5-31D4-B7CA-B5AAD9BE5E89> /opt/X11/*/libXi.6.dylib
       0x1090c6000 -        0x1094b2ff7 +libGL.1.dylib (4) <092EEE92-FC52-3C6F-A32F-1E20DFC31663> /opt/X11/*/libGL.1.dylib
       0x10959a000 -        0x10960efff +libGLU.1.dylib (5.1) <242B1D1E-3ABC-34E7-AE1E-41C94FE1E5ED> /opt/X11/*/libGLU.1.dylib
       0x10962c000 -        0x10965affb +libjpeg.9.dylib (0) <5500CEBB-26F2-39DF-9364-8903B1C286CE> /usr/local/opt/jpeg/lib/libjpeg.9.dylib
       0x109668000 -        0x109691fff +libpng16.16.dylib (43) <5A4D0BD4-F26B-3855-B459-F1B8EBC22D99> /opt/X11/*/libpng16.16.dylib
       0x1096a1000 -        0x1096fcff7 +libtiff.5.dylib (0) <464166BF-EAFF-3B49-B31F-3FC1389F5E04> /usr/local/opt/libtiff/lib/libtiff.5.dylib
       0x109710000 -        0x10978dff7 +libfreetype.6.dylib (0) <1325785E-2A41-39FE-888B-539A55D8E8D9> /usr/local/opt/freetype/lib/libfreetype.6.dylib
       0x1097ac000 -        0x1097dbfff +libfontconfig.1.dylib (0) <B0C36C06-6190-3DA7-9107-CE9362345FA5> /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib
       0x1097e9000 -        0x10980bffb +libpng16.16.dylib (0) <F666699A-02D5-3061-ADF9-B7A7E471C1E1> /usr/local/opt/libpng/lib/libpng16.16.dylib
       0x109816000 -        0x10982fff7 +libxcb.1.dylib (3) <FDEDEE32-91A5-3301-AFB5-50B8D4CCCBBD> /opt/X11/*/libxcb.1.dylib
       0x109843000 -        0x109844fff +libXau.6.dylib (7) <45CD2F7C-EDBB-3575-B883-9C397685B211> /opt/X11/*/libXau.6.dylib
       0x109849000 -        0x10984cfff +libXdmcp.6.dylib (7) <B8414558-7AF1-357E-9361-79D317C6AB28> /opt/X11/*/libXdmcp.6.dylib
       0x109855000 -        0x109862ff7 +libXplugin.1.dylib (1) <CAC780C2-5B07-313B-A3A2-74106D525846> /opt/X11/*/libXplugin.1.dylib
       0x109874000 -        0x1098acfff +libglapi.0.dylib (1) <3B8693CA-AA5E-3F8E-BE38-51482EE180F1> /opt/X11/*/libglapi.0.dylib
       0x1098cf000 -        0x1098d0fff +libXdamage.1.dylib (3) <047F8282-2B2D-344A-A297-229259A0F11A> /opt/X11/*/libXdamage.1.dylib
       0x1098d8000 -        0x1098d8fff +libX11-xcb.1.dylib (2) <C6EA3D8F-5255-3A78-B7B3-9D7066E68FCE> /opt/X11/*/libX11-xcb.1.dylib
       0x1098e2000 -        0x1098eefff +libxcb-glx.0.dylib (1) <44410977-5E82-3002-90E0-C46EBBA8B2E5> /opt/X11/*/libxcb-glx.0.dylib
       0x109907000 -        0x10990afff +libXxf86vm.1.dylib (2) <41E6682D-2FC1-33D7-AA07-4F8D82C2789C> /opt/X11/*/libXxf86vm.1.dylib
       0x10c75b000 -        0x10c7ecf47  dyld (750.6) <34A11073-9E4C-38C3-9293-7D566ABAE8B6> /usr/lib/dyld

etc.

**Comment by Youw** [comment]
Duplicates: #138
