### ISSUE TITLE
Travis CI integration issue

### ISSUE THREAD

**Issue by Youw** [libusb/hidapi#190]
hidapi Travis builds are passing, e.g.: [![Build Status](https://travis-ci.org/libusb/hidapi.svg?branch=macos-crash)](https://travis-ci.org/libusb/hidapi)
but the build results are not getting back to Github, e.g.: https://github.com/libusb/hidapi/pull/189 
![image](https://user-images.githubusercontent.com/5939659/94365565-ba18f380-00da-11eb-8df7-0e3cfc428f92.png)

Probably something wrong with Travis settings, or something.

**Comment by Youw** [comment]
@z3ntu do you happen to remember who is the owner of Travis builds configuration?

**Comment by Youw** [comment]
> @z3ntu do you happen to remember who is the owner of Travis builds configuration?

I guess it doesn't really matter.

As an Admin of libusb/hidapi I pretty much can configure Travic-CI build itself.
The issue we face is well-known: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

Just need to migrate Travis integration from Github Hooks to Github Apps.
Already created a request. @LudovicRousseau would you be able to approve?

**Comment by LudovicRousseau** [comment]
Travis-CI should have Read and Write access to libusb/hidapi

**Comment by Youw** [comment]
Yeap, everything seems to be working. Thanks.
