### ISSUE TITLE
FD 0 is a valid file descriptor

### ISSUE THREAD

**Issue by mzyngier** [libusb/hidapi#199]
I may have reported this issue against a stale repository, so here it is again:

https://github.com/signal11/hidapi/issues/462

Short story: File descriptor 0 is perfectly valid, and shouldn't be considered as an error.

https://github.com/libusb/hidapi/blob/d2c3a9862eefe2d3f4db0f00c0238277bfb4e44b/linux/hid.c#L668-L671

**Comment by z3ntu** [comment]
Relevant part from `open(2)`:

> RETURN VALUE
>        open(), openat(), and creat() return the new file descriptor (a nonnegative integer), or -1 if an error occurred (in which case, errno is set appropriately).

**Comment by Youw** [comment]
> (a nonnegative integer)

so I guess 0 is a nonnegative integer, looks valid

@mzyngier would you care to submit a PR?
