### ISSUE TITLE
hid_read() is there any way to return the correct length?

### ISSUE THREAD

**Issue by WanManito** [libusb/hidapi#230]
"hid_ Read () "is there any way to return the correct length? Like serial port and TCP communication, each read will return the actual length. Now the length is always 48, and there is a lot of irrelevant data.

**Comment by Youw** [comment]
On which platform?

**Comment by WanManito** [comment]
@Youw window10

**Comment by Youw** [comment]
> Now the length is always 48

That's probably a "maximum length" of the input report. That's a current limitation of a Windows backend implementation.

**Comment by WanManito** [comment]
![image](https://user-images.githubusercontent.com/26118508/103641165-44031300-4f8c-11eb-8e3a-d782e2a8050b.png)

I set 64 because I'm not sure how long to read. Is there a way to return the actual length

**Comment by Youw** [comment]
Not as of today.

**Comment by WanManito** [comment]
Is this problem considered to be solved in the next version? thank you

**Comment by Youw** [comment]
Sure, if someone cares to prepare a PR.
But I cannot give any guarantee.

**Comment by Youw** [comment]
I've checked the API/implementation again, and can confirm that on Windows, hidapi returns as accurate result as _possible_ for this platform.
In other words: WinAPI cannot give any better, nor hidapi.

The way hidapi is designed and originally purposed - if you want to communicate with HID device, you need to know protocol/specs of your device, including details like the size of the input/output report, in advance.

**Comment by JoergAtGithub** [comment]
Thanks for investigating! But doesn't the Windows API return the size of the HID caps? If you sum up the cap sizes per report, shouldn't you get the size of the report. Or I'm getting something wrong here?

**Comment by Youw** [comment]
In theory, it really is possible to get capabilities of a specific report (its size) and _assume_ that successfully read report is (only) of size, as specified in capabilities.

By doing so, we would start doing something what we don't do for any other platform. hidapi is designed to be a thin proxy between a user and underlying backend with _unifor API_ on each platform.
