### ISSUE TITLE
windows:Should the HidD_FlushQueue function be introduced?

### ISSUE THREAD

**Issue by uzsunliming1** [libusb/hidapi#241]
Should the HidD_FlushQueue function be introduced?
This is a function that I think is going to be used a lot, at least by me.

uzslm

**Comment by Youw** [comment]
Please clarify.

**Comment by mcuee** [comment]
HidD_FlushQueue() is Windows only.
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_flushqueue

**Comment by mcuee** [comment]
Close this since the OP does not come back.
