### ISSUE TITLE
hid_enumerate() doesn't see a device

### ISSUE THREAD

**Issue by andy-shev** [libusb/hidapi#242]
hid_enumerate(0x0d50, 0);

returns `NULL`,  while 

    % lsusb -d 0x0d50:
    Bus 003 Device 002: ID 0d50:0008 Cleware GmbH USB-Switch
    % lsusb --version
    lsusb (usbutils) 013

HID API v0.10.1.

**Comment by Youw** [comment]
1) Please don't make me guess what version of hidapi you're using, and which backend (hidraw or libusb).
2) The fact that that is a USB device, doesn't mean that it is a HID device. Please clarify what makes you think it should work.

**Comment by andy-shev** [comment]
I do not see easy way where I can read how to switch between backends, so I have no clue what the backend is in use. Is it compile time option? Seems so. Then it's hidraw. Okay, with libusb backend it works.
