### ISSUE TITLE
Missing Bluetooth dongle

### ISSUE THREAD

**Issue by smikesmike** [libusb/hidapi#246]
Hi,

I've got a Bluetooth dongle, which is not visible in `hidapi`. I am using a MacbookPro with `Big Sur v11.2.1`

Here is the `lsusb` output:

                CSR8510 A10:

                  Product ID: 0x0001
                  Vendor ID: 0x	  (Cambridge Silicon Radio Ltd.)
                  Version: 88.91
                  Speed: Up to 12 Mb/s
                  Location ID: 0x14334000 / 7
                  Current Available (mA): 500
                  Current Required (mA): 100
                  Extra Operating Current (mA): 0

Do you have an idea how I could communicate with the dongle? If I use `libusb` I get an `access denied`.

BR
Marc

**Comment by Youw** [comment]
that is a Bluetooth adapter, not a HID device

I presume you wan't to connect to one of your Bluetooth devices (e.g. to you phone, or a development board, that has a Bluetooth adapter too) using this dongle
you wan't to use [macOS Bluetooth API](https://developer.apple.com/documentation/corebluetooth) for that
