### ISSUE TITLE
Urb vendor(Control transfer) request

### ISSUE THREAD

**Issue by Lulz322** [libusb/hidapi#248]
**Yo, i want to recreate urb vendor request to a mice as seems below**

![Wireshark_vsB3fOuIfA](https://user-images.githubusercontent.com/36892265/108627801-0f75e880-7460-11eb-81bf-412ea91257be.png)

I tried to :
```
	uint8_t data[8];
	memset(test_get, 0x00, 8);

	data[0] = 0x40;
	data[1] = 0x01;
	data[3] = 0x01;
	data[4] = 0x08;
	data[5] = 0x43;

       hid_send_feature_report(device, data, 8);
```
But nothing happens :(

out from hid_error is :
```
The parameter is incorrect
```

**Is possible change bmRequestType from 0x21 to 0x40 and create URB_FUNCTION_VENDOR_DEVICE or using 0x21 request send a similar command to a mice?**

**Comment by mcuee** [comment]
Read this and you should be able to do it by yourself. Please reopen this if you still have issue. Please also take note that this will not work under Windows as hidapi will not work for mouse/keyboard under Windows.
https://www.usb.org/sites/default/files/hid1_11.pdf
