### ISSUE TITLE
how to get HID usb port information

### ISSUE THREAD

**Issue by nxpfrankli** [libusb/hidapi#250]
we have two board A and B connected to one PC, with the same chip, the same vid and pid, no serial number info.  

How to get usb port information for each board? 

https://github.com/libusb/libusb/issues/885

**Comment by Youw** [comment]
There is no "official" way. You're expected to use fields of `hid_device_info` do distinguish your devices (all, but `path`), and `serial_number` is primary for this purpose.

Unofficial way: if you know exactly the version of hidapi library you use (and not relying on a system-installed instance), you may try to parse the `path`. See https://github.com/libusb/hidapi/blob/master/libusb/hid.c#L487
But I strongly do not recommend doing so, if you could use `serial_number`s instead.
`path` is platform/backend - specific, and it won't work, for instance, if you choose to switch from libusb to hidraw backend.

Also, see https://github.com/libusb/hidapi/pull/117.

**Comment by nxpfrankli** [comment]
Our ROM have not provided serial_number info. 

Our software work well with libusb at windows and linux.  
we need a better solution cross windows, linux and macos.

**Comment by Youw** [comment]
If you need a reliable cross-platform solution - update your ROM to provide a `serial_number`.
Using `path` is not reliable nor easy to implement.

I cannot suggest you anything else.


If you wan't to continue a discussion, please use https://github.com/libusb/hidapi/discussions/categories/q-a instead.
