### ISSUE TITLE
found device, "unable to read indexed string 1" 

### ISSUE THREAD

**Issue by jyzhong** [libusb/hidapi#270]
I open my device success last weekend, now it failed.
I have the following  error info :
1: "unable to read indexed string 1" 
2: `res = hid_read(handle, buf, sizeof(buf));
   if (res == 0)
	  [printf("waiting...\n");]`
   print  lots of "waiting".
Thanks for your reply advance!
 

)

**Comment by mcuee** [comment]
You need to provide more info about the device, your codes, OS, etc.
