### ISSUE TITLE
Need binary data transfer

### ISSUE THREAD

**Issue by drmcnelson** [libusb/hidapi#290]
The recv call returns a list of ints, one int for each byte in the data received from the device.

Consider the case where the data is a structure of strings floats and ints, or pixel data from an imaging sensor that you intend to pass on to other hardware.  

Your hardware sent binary data, and the python hidapi gives it to your as list of ints, which you now have to convert back to a byte array, at the cost of copying and repacking the data.

While the list of ints might be okay for some use cases,  it is not faithful to the data and is problematic for the more general set of use cases.

Apart from fixing the api, the next best solution is provide another call that does return the data faithful to what was sent.

I suggest that this is pretty serious, and that the alternative to addressing it is that users who need true binary transfers will simply use something else.

**Comment by mcuee** [comment]
Just wondering which API are you referring to. Are you talking about cython-hidapi or hidapi itself? I will say the C HIDAPI APIs talk about unsigned char *data.

https://github.com/libusb/hidapi/blob/master/hidapi/hidapi.h
```
int  HID_API_EXPORT HID_API_CALL hid_write(hid_device *dev, const unsigned char *data, size_t length);
int HID_API_EXPORT HID_API_CALL hid_read_timeout(hid_device *dev, unsigned char *data, size_t length, int milliseconds);
int  HID_API_EXPORT HID_API_CALL hid_read(hid_device *dev, unsigned char *data, size_t length);
int HID_API_EXPORT HID_API_CALL hid_send_feature_report(hid_device *dev, const unsigned char *data, size_t length);
int HID_API_EXPORT HID_API_CALL hid_get_feature_report(hid_device *dev, unsigned char *data, size_t length);
int HID_API_EXPORT HID_API_CALL hid_get_input_report(hid_device *dev, unsigned char *data, size_t length);

```

**Comment by mcuee** [comment]
cython-hidapi is a different project.
https://github.com/trezor/cython-hidapi

**Comment by drmcnelson** [comment]
I was referring to the python hidapi

**Comment by mcuee** [comment]
In that case, I will close the issue here and please raise the issue to cython hidapi.

**Comment by drmcnelson** [comment]
Thank you, sorry for the mispost
