### ISSUE TITLE
 I am writing to 66 bytes of data and return -1 error. How to solve this problem? This instruction can be written in the manufacturer's software

### ISSUE THREAD

**Issue by a751116023** [libusb/hidapi#293]
I am writing to 66 bytes of data and return -1 error. How to solve this problem? This instruction can be written in the manufacturer's software

**Comment by mcuee** [comment]
Please provide more details. Nobody can help you based on what you have you stated.

**Comment by mcuee** [comment]
Please read this:
http://www.catb.org/~esr/faqs/smart-questions.html

They got Chinese translations as well.
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by mcuee** [comment]
Close for now. Please come back if you have new info.
