### ISSUE TITLE
Add support for errors in hid_error on MacOS

### ISSUE THREAD

**Issue by hardkrash** [libusb/hidapi#310]
The `IOreturn` value can be passed to the c library function `mach_error_string` to provide the error string for the error that was raised.

`mach_error_string` is defined in [mach_error.h](https://opensource.apple.com/source/xnu/xnu-2422.1.72/libsyscall/mach/mach/mach_error.h.auto.html)

`char *mach_error_string(mach_error_t error_value);`  and a `IOReturn` is a version of `mach_error_t`

**Comment by mcuee** [comment]
@hardkrash Please help to create a pull request. Thanks.

**Comment by Youw** [comment]
Oh, this is done as part of https://github.com/libusb/hidapi/pull/314.
Available in the latest release.
