### ISSUE TITLE
Next release 0.11 

### ISSUE THREAD

**Issue by mcuee** [libusb/hidapi#327]
From the github Projects page, #133 and #146 are planned. Probably they can be delayed.
https://github.com/libusb/hidapi/projects/2

**Comment by mcuee** [comment]
#280 is ready.
#309 is more or less ready.
#164 is said to need a bit of work.

**Comment by mcuee** [comment]
Reference: https://github.com/trezor/cython-hidapi/issues/116
A new release will help downstream project.

**Comment by Youw** [comment]
Good summary, thanks. I'll try to get my hands to it by the end of the week.

**Comment by Youw** [comment]
Release draft is ready.
As soon as we check/merge #334 - I'll attach Windows binaries to the release and will fire a v0.11.0,

**Comment by mcuee** [comment]
Looks like we are ready now that #334 is merged.

**Comment by Youw** [comment]
Done: https://github.com/libusb/hidapi/releases/tag/hidapi-0.11.0
