### ISSUE TITLE
Add CI build badges

### ISSUE THREAD

**Issue by Qbicz** [libusb/hidapi#35]
Blocked by https://github.com/libusb/hidapi/pull/34

Badges look like this: https://builds.sr.ht/~qbicz/hidapi-1/archlinux.yml

**Comment by z3ntu** [comment]
We can use

[![builds.sr.ht status](https://builds.sr.ht/~qbicz/hidapi.svg)](https://builds.sr.ht/~qbicz/hidapi?)
```
[![builds.sr.ht status](https://builds.sr.ht/~qbicz/hidapi.svg)](https://builds.sr.ht/~qbicz/hidapi?)
```
now. This should display a "combined view" of the different builds for hidapi (so if a build for e.g. FreeBSD fails, this badge should change). I'm unsure how (failing) pull requests will affect this badge though.

**Comment by Youw** [comment]
it seems that is shows the status of the last build
branch-specific badges are not available yet (at least as per this discussion): https://todo.sr.ht/~sircmpwn/builds.sr.ht/137

it worth to try, but if I need to guess - I'd say, that failed PR will make a failed badge

**Comment by Youw** [comment]
one more note:

Travis supports per-branch badges, like this:
[![Build Status](https://travis-ci.org/libusb/hidapi.svg?branch=master)](https://travis-ci.org/libusb/hidapi)
`[![Build Status](https://travis-ci.org/libusb/hidapi.svg?branch=master)](https://travis-ci.org/libusb/hidapi)`

**Comment by Qbicz** [comment]
This will be perfect to use last master build, I'm also fine with having a separate badge for each platform (I have impression the project look more stable this way). I guess we can integrate the combined badge and change it later if we see it is problematic.

**Comment by Qbicz** [comment]
We can also add AppVeyor badge when https://github.com/libusb/hidapi/pull/37 is available.
