### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by mcuee** [libusb/hidapi#36]
Wiki page is good to have.

**Comment by Youw** [comment]
Maybe, instead of Github Wiki page go for https://github.com/libusb/hidapi/issues/5 ?

**Comment by z3ntu** [comment]
#5 should be a real website imo.

**Comment by Qbicz** [comment]
I agree with @Youw and @z3ntu to go for #5 and a website. We can point to the website from README and point to it from Wiki or disable Gituhb Wiki at all.
