### ISSUE TITLE
[Solved, my fault] usagepage not correct

### ISSUE THREAD

**Issue by ednt** [libusb/hidapi#400]
Hi,

I just downloaded and tested hidapi, because it would be nice to have also access to the bluetooth devices.
But ...
My program with direct win api access results in:

6993:B017 Yealink: HID debug interface UP: FF01 512/512
046A:B090 Cherry: USB keyboard UP: 1 2/0
046A:B090 Cherry: USB keyboard UP: C 4/0
046A:B090 Cherry: USB keyboard UP: FF00 0/0
6993:B017 Yealink: Yealink WH62 UP: B 3/2
6993:B017 Yealink: Yealink WH62 UP: C 8/0
6993:B017 Yealink: Yealink WH62 UP: FF30 3/2
6993:B017 Yealink: Yealink WH62 UP: FF00 1024/1024
6993:B017 Yealink: Yealink WH62 UP: FF99 0/0
6993:B017 Yealink: Yealink WH62 UP: FF99 2/0

The hidapi results in:
6993:B017 FF01 4 Yealink HID debug interface
046A:B090 FF01 4 Cherry USB keyboard
046A:B090 FF01 4 Cherry USB keyboard
046A:B090 FF01 4 Cherry USB keyboard
046A:B090 FF01 4 Cherry USB keyboard
6993:B017 FF01 4 Yealink Yealink WH62
6993:B017 FF01 4 Yealink Yealink WH62
6993:B017 FF01 4 Yealink Yealink WH62
6993:B017 FF01 4 Yealink Yealink WH62
6993:B017 FF01 4 Yealink Yealink WH62
6993:B017 FF01 4 Yealink Yealink WH62

The usagepage is never updated during hid_enumeration.

Win10 x64 compiled with VS2015 to x86

**Comment by Youw** [comment]
Care to share more details?
- HIDAPI version/build;
- Source sample for:
  1) > My program with direct win api access
  2) > The hidapi results

**Comment by ednt** [comment]
I downloaded the hidapi yesterday (directly from here).
So it is the latest version.
I wrote already how I built it.

I posted already the output
I used hid_enumerate() and went over all entries of the list.
The output is generated by the line:

`Debug RSet(Hex(*hdiPtr\vendor_id), 4, "0") + ":" + RSet(Hex(*hdiPtr\product_id), 4, "0") + " " + Hex(*hdi\usage_page) + " " + Hex(*hdi\interface_number) + " " + *hdiPtr\manufacturer_string + " " + *hdiPtr\product_string + " " + PeekS(*hdiPtr\path, -1, #PB_Ascii)`

My program with direct win api access uses:
`If HidD_GetPreparsedData(hDevice, @PreparsedData)
        HidP_GetCaps(PreparsedData, *Capabilities) 
        HidD_FreePreparsedData(PreparsedData)
        result = #True
      EndIf `
To get the usage_page.

**Comment by ednt** [comment]
I just added a log to hid_device_info()
dev->usage_page shows the right values.

Ok, found the bug: my fault.
Sorry for disturbing you.
As you can see above, I used the wrong pointer for usage_page and interface_number.

**Comment by Youw** [comment]
> I posted already the output

And I was specifically asking for _source_ sample for "the hidapi results".

> I used the wrong pointer

Specifically for this reason.
