### ISSUE TITLE
Is it possible to send/read data from/to HID-keyboards under Windows?

### ISSUE THREAD

**Issue by xcme** [libusb/hidapi#402]
Hello,

The title is the question. I compiled hidtest.exe and it can enumerate devices. I see my keyboard there and I placed its ID to the _hid_open_ function. It then provides some details about the device, but some functions fail:

```
Unable to send a feature report.
Unable to get a feature report.
Incorrect function.Unable to write()
Error: Incorrect function.
Unable to write() (2)
```

I heard that Windows allegedly has some limitations for HID keyboards and mices, but [this](https://github.com/CalcProgrammer1/OpenRGB) project can work with my keyboard. Thus, it should be possible.

**Comment by Youw** [comment]
Use [discussions](https://github.com/libusb/hidapi/discussions) for this kind of questions.
