### ISSUE TITLE
Overlapped I/O operation is in progress.

### ISSUE THREAD

**Issue by mandar1jn** [libusb/hidapi#433]
I'm trying to write to a HID device, but I keep getting the same error. The error in question being ``hid_write/WaitForSingleObject: (0x000003E5) Overlappende I/O-bewerking wordt uitgevoerd.``. Note that this is Dutch. The translation would be ``hid_write/WaitForSingleObject: (0x000003E5) Overlapping I/O-changes are being made.`` I'm not exactly sure if "changes" is the correct translation. 

The device in question is a Skylanders portal. Other applications seem to work fine, but when I try to write to it doesn't work.
My code to write to the portal is:
```cpp
unsigned char buffer[0x21];
	memset(buffer, 0, 0x21);

	buffer[1] = 'C';

	buffer[4] = 0xFF;

	for (int i = 0; i < 10; i++)
	{
		if (hid_write(portal->handle, buffer, 0x21) == -1)
		{
			printf("Failed to write. Attempt: %d\n", i);
			wprintf(hid_error(portal->handle));
			printf("\n");
		}
		else
		{
			break;
		}
	}
```
	The device discovery code is:
```cpp
	struct hid_device_info* list, * attributes;

    wchar_t wstr[255];

    handle = NULL;

    list = hid_enumerate(0x0, 0x0);

    if (!list) {
        printf("unable to open USB devices\n");
        exit(1);

    }
    attributes = list;
    while (attributes) {
        if (((attributes->vendor_id == 0x12ba) || (attributes->vendor_id == 0x54c)) ||
            (attributes->vendor_id == 0x1430)) {
            if ((attributes->product_id == 0x150) || (attributes->product_id == 0x967)) {
                printf("Found portal usb device\n");
                int err;

                handle = hid_open(attributes->vendor_id, attributes->product_id, NULL);
                if (handle == NULL) {
                    printf("Error communicating with Portal.\n ");
                }

                /*
                wstr[0] = 0x0000;
                err = hid_get_manufacturer_string(hPortalHandle, wstr, MAX_STR);
                if (err < 0)
                    printf("Unable to read manufacturer string\n");
                printf("Manufacturer String: %ls\n", wstr);
                // Read the Product String
                wstr[0] = 0x0000;
                err = hid_get_product_string(hPortalHandle, wstr, MAX_STR);
                if (err < 0)
                    printf("Unable to read product string\n");
                printf("Product String: %ls\n", wstr);
                // Read the Serial Number String
                wstr[0] = 0x0000;
                err = hid_get_serial_number_string(hPortalHandle, wstr, MAX_STR);
                if (err < 0)
                    printf("Unable to read serial number string\n");
                printf("Serial Number String: (%d) %ls", wstr[0], wstr);
                printf("\n");
                */

                break;
            }
        }
        attributes = attributes->next;
    }
    hid_free_enumeration(list);

    if (!handle) {
        printf("Cannot Find Portal USB.\n");
        exit(1);
    }
```
I copied this from another project, but it seems to find the portal just fine and I am able to read incoming data using hid_read.

**Comment by mandar1jn** [comment]
Okay. So the correct error translation is: ``Overlapped I/O operation is in progress.``

**Comment by Youw** [comment]
Can you confirm you're opening the device with correct usage_page/usage?

**Comment by mandar1jn** [comment]
hid_open does not have a usage page variable

**Comment by Youw** [comment]
Use what you call `attributes` to filter for the correct usage_page/usage, and then `hid_open_path(attributes->path)`.

**Comment by Youw** [comment]
Can you confirm that your device doesn't use numbered reports, and the only report you have is 20 bytes long?

**Comment by mandar1jn** [comment]
also, I updated my portal finder to just
```cpp
struct hid_device_info* devices;

    handle = NULL;

    devices = hid_enumerate(0x1430, 0x0150);

    if (!devices) {
        printf("unable to open USB devices\n");
        exit(1);

    }
    
    handle = hid_open_path(devices->path);

    hid_free_enumeration(devices);

    if (!handle) {
        printf("Cannot Find Portal USB.\n");
        exit(1);
    }
```

**Comment by Youw** [comment]
> also, I updated my portal finder to just

My point is that your device may have several usage_page/usages, and each unique pair is reported as a separate device.
And the report you're interesting is tight to a specific usage_page/usages.
It may happen, that you're using a "wrong" device to `hid_write`.

> I'm pretty sure it does not use numbered reports

But what is the size of the report?
I can predictably tell what happens if you pass more data to the `hid_write` than the report size.

**Comment by mandar1jn** [comment]
Enumerate only results in a single device. And similar programs also use a 32 byte buffer

**Comment by Youw** [comment]
> similar programs also use a 32 byte buffer

With the same device?

**Comment by mandar1jn** [comment]
Yes. With the same device.

**Comment by mandar1jn** [comment]
“Working”. There are several projects, but they’re all years old. And either: 1. Don’t compile 2. Don’t support visual studio. For the ones I could get binaries off, they work just fine. I don’t know why my code doesn’t.

**Comment by mandar1jn** [comment]
One thing I did notice is that when using a usb monitor my code’s data uses bulk and interrupt where at least one other reports using interface. Weirdly enough, this code also uses hidapi and hid_write

**Comment by mandar1jn** [comment]
I’ll try and get some screenshots of this tomorrow to show what I mean.

**Comment by mandar1jn** [comment]
Oh. Something I forgot to note: the device constantly sends status packets. This might be the origin of the original error. Should have told that earlier.

**Comment by Youw** [comment]
> the device constantly sends status packets

That shouldn't matter.

**Comment by mandar1jn** [comment]
No. A version from at the latest 2017. https://github.com/capull0/SkyDumper This is the project some of my code is based off of. The hidapi files don’t seem to contain a version definition

**Comment by mandar1jn** [comment]
Okay. Looking at the source of the reference program I used, the hid files are either really old, or manually modified.

**Comment by mandar1jn** [comment]
Yes. I think they modified the hid write function.
