### ISSUE TITLE
32bit Usage items are not supported by get_usage of libusb backend

### ISSUE THREAD

**Issue by JoergAtGithub** [libusb/hidapi#454]
The USB standard allows it to specify a usage in two ways:
- Fully qualified as one single 4 byte report descriptor Usage item
- Seperated in an 1 or 2 byte Usage-Page item, followed by an 1 or 2 byte Usage item
The get_usage function of the libusb backend supports only the second.

From USB HID spec 1.11 page 17:
![grafik](https://user-images.githubusercontent.com/64457745/189529023-f800f2e9-85b2-4bac-bfce-68b17604c11a.png)

From USB HID spec 1.11 page 35:
![grafik](https://user-images.githubusercontent.com/64457745/189529415-61ed0bc9-b26b-4b7e-b16d-a3b63b018589.png)

**Comment by mcuee** [comment]
Is it because most of the USB HID Devices use the second way that we have not seen bug report for thr libusb backend?

**Comment by Youw** [comment]
Yes, likely
