### ISSUE TITLE
HID read normal but write return value is always 63

### ISSUE THREAD

**Issue by arilink** [libusb/hidapi#508]
windows 10   
version: hidapi 0.13.1
hid_read is normal, but hid_write always returns 63 and no out message is detected by bus hound

**Comment by arilink** [comment]
![12fa8614690192e4792a4529d1b3567](https://user-images.githubusercontent.com/97713657/219527062-147b9cf3-ae8d-494e-bf30-4ea8a7c91e99.png)
![e95c395fa79d209ff6fa7d3d403b49d](https://user-images.githubusercontent.com/97713657/219527070-82c0dec9-f96f-4c24-abb7-8222e49c0c7f.png)

**Comment by arilink** [comment]
I use bus hound to send data to the device, and bus hound can also observe hid out messages, but the return value of hid api write is always 63 and bus hound does not capture out messages

**Comment by Youw** [comment]
Depending on device capabilities - the Output report (hid_write) might be sent over Interrupt pipe or over Control pipe.
Input reports (hid_read) are always received over Interrupt pipe.

Try catching Usb Control too.

**Comment by arilink** [comment]
The device has a separate out endpoint, will it still send data through the control pipeline?

**Comment by Youw** [comment]
It should, but just to be sure.

One more thing: so the data is not being received by the device?

**Comment by arilink** [comment]
No The device has not received the data sent from the host computer

**Comment by arilink** [comment]
My device defines the out endpoint and uses bus hound to send commands to the device indicating that the device is working fine but I use hidapi to send commands to the device for control and out endpoints and no data is coming out

**Comment by JoergAtGithub** [comment]
Does the device describes the report, which you try to send, in the HID ReportDescriptor?

**Comment by arilink** [comment]
Yes. The device report descriptor has the out descriptor

**Comment by JoergAtGithub** [comment]
Could you please share the HID ReportDescriptor.

**Comment by arilink** [comment]
I can't send data to the device using libusb but my friend can send data to the device using a tool made in c#  which is weird

**Comment by arilink** [comment]
my email is root@arilink.com    You send me an email and I will send you the descriptor by email

**Comment by arilink** [comment]
[USBlyzer Report.pdf](https://github.com/libusb/hidapi/files/10768646/USBlyzer.Report.pdf)
This is HID ReportDescriptor
Thank you very much for your help

**Comment by JoergAtGithub** [comment]
Which ReportID has the OutputReport which you try to send, and what is the size in data in bytes you try to send?

**Comment by arilink** [comment]
I want to send data to report id = 1

**Comment by Youw** [comment]
Can you share the sample of you code that is using HIDAPI?

**Comment by JoergAtGithub** [comment]
There is no OutputReport with Report ID 1 and size of 8 bytes in this report descriptor.

**Comment by arilink** [comment]
[code.txt](https://github.com/libusb/hidapi/files/10769072/code.txt)
This is code

**Comment by arilink** [comment]
![85c0c60c13c99163ec510c760bbb867](https://user-images.githubusercontent.com/97713657/219716494-d9168dfa-2623-4ce8-addb-bb3b641f414d.png)
Should I add the out description to the report id 1 like this?

**Comment by JoergAtGithub** [comment]
The descriptor is fine, you just need to send the same number of bytes as defined in the descriptor. Otherwise Windows rejects it.

**Comment by arilink** [comment]
This device belongs to the client, and I am only responsible for developing the upper computer and communicating with it. The information the client gave me was to send data less than 64 bytes to report 1, but I did not find the relevant definition of out in the top collection

**Comment by arilink** [comment]
Any suggestions I'm confused about what to fix

**Comment by JoergAtGithub** [comment]
For ReportID 1: Try to send 14 bytes to the joystick and 1 byte to the keyboard

**Comment by arilink** [comment]
I send 14 bytes and the result is the same: 63

**Comment by arilink** [comment]
> For ReportID 1: Try to send 14 bytes to the joystick and 1 byte to the keyboard

why 14 bytes?

**Comment by JoergAtGithub** [comment]
You need to sum up all bits of the Report. All ReportSize x ReportCount. The byte with the ReportID comes on top.

**Comment by Youw** [comment]
> I send 14 bytes and the result is the same: 63

I believe it is a limitation of WinAPI. It expects/reports buffers of size that is the size of largest report.

**Comment by Youw** [comment]
Can you debug the HIDAPI and check if your device is opened in ReadWrite or ReadOnly mode?
This is the fallback and the description why it is needed: https://github.com/libusb/hidapi/blob/4ebce6b5059b086d05ca7e091ce04a5fd08ac3ac/windows/hid.c#L841

**Comment by arilink** [comment]
This report descriptor is actually divided into 2 parts: 1 is JoyStick and 2 is USB HID->PID(about game force feed back). I want to send data to the Device without interfering with 2 Does this mean I need to add the relevant description of out after JoyStick?

**Comment by arilink** [comment]
How to check device is opened in ReadWrite or ReadOnly mode?

**Comment by Youw** [comment]
Step into the `hid_open_path` and check if the code I mentioned above (`open_device(interface_path, FALSE);`) is executed or does it succeed at `open_device(interface_path, TRUE);`.

**Comment by arilink** [comment]
The Qt Creator Cannot step into hid_open_path

**Comment by Youw** [comment]
> The Qt Creator Cannot step into hid_open_path

Probably because you didn't build it yourself.

**Comment by arilink** [comment]
Yes. i use hidapi  dll

**Comment by arilink** [comment]
![image](https://user-images.githubusercontent.com/97713657/219750911-1c8d0ff4-388c-4b81-b123-52ef336f4716.png)
Can I read and write correctly if I add the right part to where the left arrow points?

**Comment by Youw** [comment]
I'm not sure I follow.

Have you tried to filter/open the device with `usage_page/usage`=`1/5`? Does the hid_write works in that case?

**Comment by arilink** [comment]
![image](https://user-images.githubusercontent.com/97713657/219820185-58d59b70-b150-43f7-acb3-b82a43bd54d0.png)

**Comment by Youw** [comment]
Based on this:
![image](https://user-images.githubusercontent.com/5939659/219873696-ec67c510-21bd-49f7-bdfe-f9706500b0d8.png)
I assume you should have one.

Can you share the entire HID Report Descriptor as reported by the device?
Can be done on macOS on Linux (e.g. with https://github.com/DIGImend/usbhid-dump).

**Comment by JoergAtGithub** [comment]
> Can you share the entire HID Report Descriptor as reported by the device?

He did above: https://github.com/libusb/hidapi/issues/508#issuecomment-1434859965

**Comment by Youw** [comment]
Ah, sorry, I missed that. I'll check, thanks.

**Comment by mcuee** [comment]
It seems to me the following code is not really opening the right device path.

```
int MainWindow::hid_print()
{
    hid_device_info *hid_info;//usb链表
    hid_device_info *tar_info;
    char *path = nullptr;
        /*打开指定VID PID设备*/
    hid_info = hid_enumerate(0x11ff,0x1112);
    /*遍历所有信息并打印*/
    for(;hid_info != nullptr;hid_info = hid_info->next){
        if(hid_info->interface_number==0)
        {
            qDebug("设备接口号:%d",hid_info->interface_number);
            qDebug("厂商字符串:%ls",hid_info->manufacturer_string);
            qDebug("设备字符串:%ls",hid_info->product_string);
            qDebug("版本号:%d",hid_info->release_number);
            qDebug("地址:%s",hid_info->path);
            tar_info = hid_info;
            path = hid_info->path;
        }

    }
    qDebug("地址:%s",path);
    /*释放链表*/
    hid_free_enumeration(hid_info);
    //handle = hid_open(0x11ff,0x1112,nullptr);
    handle = hid_open_path(path);
```

@arilink 

You may want to print out the output from the hidtest program and from there you should know how to open the right device path.
https://github.com/libusb/hidapi/tree/master/hidtest

**Comment by arilink** [comment]
@mcuee  @Youw  @triplef   The problem has been fixed. Thank you very much for your help

**Comment by Youw** [comment]
Care to share what was the issue or how it was fixed?

**Comment by arilink** [comment]
You may not believe that it is a CPU problem. The computer with the problem I tested was installed with an AMD processor. Using BusHound, I have been unable to capture the out data in the program, but I switched to another computer with an Intel processor. Everything is normal. The two computers. The windows system version is the same as the bushound and QT software versions, so it has nothing to do with HIDAPI

**Comment by mcuee** [comment]
I tend to think this is rather a chipset problem. I remember AMD platforms sometimes have problem for USB because of USB Bus Filter. This might cause problems for Bus Hound.

**Comment by Youw** [comment]
Yeah, for some reason I'm not suprised either.

**Comment by arilink** [comment]
@mcuee  @Youw  @triplef  Yes, I have consulted some engineers and they said that it does happen. Fortunately, my problem has been solved. Thank you very much for your help
