### ISSUE TITLE
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so 

### ISSUE THREAD

**Issue by BobbyCirrus** [libusb/hidapi#518]
Hi, ....

I got 'importError' when I run 'import hid' 0n my python..
I selected interpreter to Python. 3.8.19

THX in advance for any guide.

I had 'pip install hidapi', but unable to fix issue.

=======================================
import hid

=================================================
File [c:\Users\xxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\hid\__init__.py:30]

else:
    error = "Unable to load any of the following libraries:{}"\
        .format(' '.join(library_paths))
 -->    raise ImportError(error)
hidapi.hid_init()
atexit.register(hidapi.hid_exit)
===========================================
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dl
=====================================
Regards

**Comment by Youw** [comment]
The HIDAPI repo is a C library - it does not providea python wrappers (even though such exist).
You're probably trying to use [cython-hidapi](https://github.com/trezor/cython-hidapi).

Make sure you've read all of its documentation before opening an issue.
