### ISSUE TITLE
Request for help implementing HID protocol in BrailleTouch project

### ISSUE THREAD

**Issue by discapacidad5** [libusb/hidapi#524]
Hello,

I hope this message finds you well. I am reaching out to you because I am working on an open-source project called BrailleTouch. Our goal is to create affordable Braille displays for blind and deaf-blind individuals.

We are currently stuck and unable to get the HID Braille to receive information from the screen reader and continue programming. As someone with experience in this area, your expertise could be of great help to our project.

I believe that an open-source Braille display could be incredibly useful and have many benefits for those who are blind and deaf-blind. Your knowledge of the HID protocol could be particularly helpful in implementing the protocol in our Braille display.

Please take a moment to review our project on GitHub at https://github.com/brailletouch. If you're interested in helping, please let me know.

Thank you for your time and consideration. I look forward to hearing back from you.

Best regards,

Cergio Monasterio

**Comment by Youw** [comment]
This is an issue tracker, not a support forum.
At most you may open a discussion under: https://github.com/libusb/hidapi/discussions/categories/support-request
