### ISSUE TITLE
The write method is called continuously in the thread

### ISSUE THREAD

**Issue by Alvazz** [libusb/hidapi#532]
I run the write method in a thread, which means that I keep sending data to the hid hardware device, can I do this?

**Comment by Youw** [comment]
Generally, sending data continuesly is definitely something HIDAPI is designed for.
But if you send data in one thread and doing something else in another w/o syncronisation - that is not thread-safe.

As of current moment, all HIDAPI function over a particular hid_device must be done either in one thread, or serialized using some syncronisation mechanism.
The only exception is `hid_read(_timeout)` - that one might be used in another thread w/o syncronisation.

**Comment by Alvazz** [comment]
![image](https://user-images.githubusercontent.com/50744096/233025247-c956d636-df93-4683-81f5-79dffa3d26bf.png)
I took a look at the Hidapi.c file and found that the place that suggested this error is here.

**Comment by Youw** [comment]
Your `writeOtherData` and `writeMusicData` are not syncronized - that is a race condition and not a supported scenario.

**Comment by Alvazz** [comment]
Thank you for your enthusiastic reply, so how should I operate? For example can I use a lock-free queue to achieve this? My idea is, for example, if I have 10 pieces of data that need to be sent to the target device continuously, can I create 10 lock-free queues, insert each piece of corresponding data into each lock-free queue, and then Sent by 10 threads separately, can I do this? Or, hid_write can only be used in one thread, and hid_write cannot be called in multiple threads at the same time?

**Comment by Alvazz** [comment]
Thanks!
