### ISSUE TITLE
hidapi 0.14.0 release

### ISSUE THREAD

**Issue by mcuee** [libusb/hidapi#540]
Now we have zero outstanding PRs. Just wondering if it is good to have 0.14.0 release soon.

If I look at the Project, it is for hotplug support, which will take sometime.
https://github.com/libusb/hidapi/projects/7

**Comment by mcuee** [comment]
@Youw 

One of the good argument for a new release is because of #531. PR #534 has been merged to fix the issue for macOS 13.3 users.

**Comment by mcuee** [comment]
Reference:
* https://github.com/ruabmbua/hidapi-rs/issues/115

**Comment by mcuee** [comment]
Reference:
* https://github.com/ruabmbua/hidapi-rs/issues/104

**Comment by Youw** [comment]
I think it makes sense to fix issues found by Coverity before the release.
#541, #542 
I want to run Coverity on all platforms and apply fixes if any.
Then we're good to release.

**Comment by Youw** [comment]
https://github.com/libusb/hidapi/releases/tag/hidapi-0.14.0
