### ISSUE TITLE
connection-callback  branch cpu usage is very high

### ISSUE THREAD

**Issue by Alvazz** [libusb/hidapi#567]
pls check it!

```
if (hid_init())
		return;

	hid_hotplug_register_callback(0x0213, 0xA22C,
				      HID_API_HOTPLUG_EVENT_DEVICE_ARRIVED |
					      HID_API_HOTPLUG_EVENT_DEVICE_LEFT,
				      HID_API_HOTPLUG_ENUMERATE,
				      device_callback, NULL, &token2);
```

**Comment by Alvazz** [comment]
Let me describe it more clearly, when I don't plug in the device (0x0213, 0xA22C), the CPU usage is not high, but when I plug in the device, the CPU instantly rises to 9%~11%

**Comment by mcuee** [comment]
Please provide more details about the device (eg: output from hidtest) and OS you are using.

**Comment by d3xMachina** [comment]
On my end I only have 0.05% cpu usage when a device gets connected with the connection-callback branch and my application does a number of things at the same time. My config is Windows 11 and a 13600k cpu.

Make sure you keep your code in the callback as concise as possible. You can use a producer-consumer pattern with a FIFO to process those connections/disconnections in another thread.

**Comment by mcuee** [comment]
@Alvazz 

Any updates? Thanks.

We will close the issue if there are no responses.
