### ISSUE TITLE
Binding for Golang

### ISSUE THREAD

**Issue by sstallion** [libusb/hidapi#586]
Hello,

I've been maintaining a Golang binding for a few years now that has been picking up in use lately. I noticed on the Wiki there wasn't an existing binding for Golang, so I figured I would reach out and see if there's any interest in adding a link to the project: https://github.com/sstallion/go-hid.

Cheers!

**Comment by mcuee** [comment]
Done.

**Comment by sstallion** [comment]
Thanks!
