### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by z3ntu** [libusb/hidapi#6]
I'm working on CI scripts for:

| Target | CI provider | Duration | Notes |
|--------|----------| -- | -- |
|msbuild|AppVeyor|20 sec||
|cygwin|AppVeyor|1 min 45 sec||
|mingw|builds.sr.ht|70 sec|Cross-compiled on Fedora|
|freebsd|builds.sr.ht|55 sec||
|macos|Travis CI|53 sec||
|alpine|builds.sr.ht|30 sec||
|archlinux|builds.sr.ht|28 sec||

This makes sure at least that hidapi builds for most/all supported platforms.

**Comment by Qbicz** [comment]
That's very interesting, please share the results when you have the CI setup ready.

Which of these platforms can be integrated with GitHub, e.g. to run when a pull-request is opened?
Also, would it be possible to download artifacts from them? (ideally shared libraries for Windows and Mac)

**Comment by z3ntu** [comment]
You can see the results for all the platforms listed above at https://github.com/z3ntu/hidapi/commits/ci . All of them are fully integrated into GitHub ;)

Artifacts are definitely possible on AppVeyor, but I'm not sure if Travis supports artifacts natively. But honestly, it's really easy to compile hidapi on macOS, so I wouldn't actually bother with that. Windows, sure, it's a pain otherwise.

**Comment by Qbicz** [comment]
Sounds good!

What about attaching the Windows DLL to the next release? Do you think it would be a good idea? (I can provide MSVC-built library). Then having the artifacts is not essential.

**Comment by z3ntu** [comment]
I also have https://github.com/signal11/hidapi/pull/324 on my CI branch which is needed for the Windows build. 

I'll work on the Windows dll artifacts tomorrow!

**Comment by Youw** [comment]
I'd suggest switching to CMake instead of having MSVC2015/2017/2019/etc. projects.
Personally I'm using CMake for all my projects on all platforms (Windows/Linux/macOS/cross-aarch64).

**Comment by z3ntu** [comment]
Windows DLL artifacts now work: https://ci.appveyor.com/project/z3ntu/hidapi/builds/25095767/job/q9378cp84do5qs49/artifacts

**Comment by Youw** [comment]
I'd say having only a DLL as an artifact is not enough.
Perfect case, if we have .dll, .lib and .pdb - that's very common for Windows.

**Comment by z3ntu** [comment]
https://ci.appveyor.com/project/z3ntu/hidapi/build/job/f2h18kwiw3kqo2qx/artifacts Better?

**Comment by Youw** [comment]
I don't believe `hidtest.exe` is a required artifact for this library.

**Comment by z3ntu** [comment]
No it isn't but I think it doesn't hurt including that there.

**Comment by jdk** [comment]
I’m heavily in favor of leaving it, otherwise we should include it as part of the release downloads for convenience.

**Comment by Youw** [comment]
Yeah, actually, not having those in the release downloads - is my bigger concern.

**Comment by Qbicz** [comment]
@z3ntu this is great work, thanks! I downloaded the Windows artifacts and tested. It looks like the hidapi.dll is built as 32-bit, despite of name of the build `arch=x64`. It cannot be loaded with 64-bit Python, but works with 32-bit Python.

The reason I think is that you build there a 64-bit Cygwin version and 32-bit MSVC version, but only the MSVC DLL is copied as artifact. This would be really great to have 64-bit artifact available as well.

**Comment by Qbicz** [comment]
If this would be helpful, I have 64-bit target added to MSVC project here (apart from update to VIsual Studio 2017) https://github.com/Qbicz/hidapi-1/commit/a0a00ca76bbc6a2bad1b235f23c96fac6853c30b

**Comment by Qbicz** [comment]
For me we can close this, as https://github.com/libusb/hidapi/pull/34 was successful.

One thing that could be added is 64-bit Windows artifacts, @z3ntu will you have time for this? Or should we create a separate task to be picked up later by someone?

**Comment by z3ntu** [comment]
Create a new issue for that anyways, but I'll have a look at it tomorrow
