### ISSUE TITLE
Windows installation instructions

### ISSUE THREAD

**Issue by philpagel** [libusb/hidapi#604]
Thanks for a great project! I have been using hidapi on LINUX for a while.  Now also need it on Windows. I found the release files without problem but now I have no idea what to do with them. The section on installation doesn't say anything about Windows. Can someone point me in the right direction, please?

**Comment by Youw** [comment]
Windows is its own ecosystem, when it comes to shared libraries and deploying your application, its dependencies.
HIDAPI had to special handling of Windows apart of what CMake offers of-the-box.

If you where able to build/install the HIDAPI (with or w/o custom CMAKE_INSTALL_PREFIX), all you need to do to build your application - is to make sure CMake can find the HIDAPI package, which it sarches in a [variety of possible ways](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure).

[Here](https://github.com/libusb/hidapi/blob/98ab22a33d326e5f3b139d16fd0859fb811c548a/.github/workflows/builds.yml#L235) is one example in our CI script.
