### ISSUE TITLE
Is it possible to replicate this behaviour using libusb on linux?

### ISSUE THREAD

**Issue by GobGeeklord** [libusb/hidapi#613]
Hi there,

I'm trying to implement a card reader controller for a reader which only have official support for windows, but i'm trying to figure it out if there is any way to implement the behaviour using libusb: sending commands, and read the result.

This is what i can see from a usb sniffing session:

There is a SET_REPORT request/response (where we post 3 bytes as the command identifier) and then a GET_REPORT request/response (With the response from the reader)

<img width="1385" alt="image" src="https://github.com/libusb/hidapi/assets/85292943/9100b327-d18e-4c18-8af0-237d00f2fccf">

Is there any way to have this working? libusb, hidapi

Thanks in advance

**Comment by Youw** [comment]
Maybe there is, hard to tell.

But this is not a support forum - this is an issue tracker for HIDAPI library.
Unless you have an issue/but/suggestion/improvement to HIDAPI _implementation_ - this is not a place for questions like this.
