### ISSUE TITLE
HIDAPI error: ReadFile(0x00000005) denied access

### ISSUE THREAD

**Issue by Fly2023-HM** [libusb/hidapi#614]
development environment: windows11

occurs when I read the data, how to solve it,

thanks

**Comment by Youw** [comment]
What kind of device are you trying to open/read?

**Comment by Youw** [comment]
How do you ensure you really do have permissions to read from that device?

**Comment by Fly2023-HM** [comment]
thans for this reply

reason: HIDAPI won't work keyboards and mic on windows, 

the development device is similar to the above devices

by modifying the device descriptor to a user-defined device ， solve it.
