### ISSUE TITLE
hidapi_darwin.h is not installed with autotools builds

### ISSUE THREAD

**Issue by ryandesign** [libusb/hidapi#620]
When using the autotools build system on macOS, the hidapi_darwin.h header is not installed. The only installed header is hidapi.h. I tested versions 0.12.0 and 0.14.0. I am aware that the autotools build system is deprecated.

**Comment by Youw** [comment]
> I am aware that the autotools build system is deprecated.

Than you should understand why I'm closing this one.

**Comment by mcuee** [comment]
@Youw 

Maybe we want to remove the auto-tools stuff in the next version so that people will not get confused.

**Comment by Youw** [comment]
> Maybe we want to remove the auto-tools stuff in the next version so that people will not get confused.

The justification for #622 has some point. I'll have that discussion first.
And again - we've had that discussion in the past and agreed to obsolete Autotools completely when API v1 is developed. And that is a huge piece of work.
Removing Autotools completely will be very strong motivation to move to CMake, but I can imagine that it not always easy/possible for some users.

**Comment by ryandesign** [comment]
> Than you should understand why I'm closing this one.

That's up to you. I'm a developer with MacPorts. When we find problems in the software that we have in our collection, we try to report those problems to the upstream developers so that they can take whatever action they deem best.
