### ISSUE TITLE
Coverity Scans reports available

### ISSUE THREAD

**Issue by LudovicRousseau** [libusb/hidapi#63]
A long time ago I registered the hidapi project at Coverity Scans https://scan.coverity.com/faq
The project should be available at https://scan.coverity.com/projects/hidapi?tab=overview

I can add any other member of this hidapi project to have access to the Coverity Scans results. Just connect  on Coverity Scans and ask for an access to the hidapi results.

For now only 2 issues are reported by Coverity Scans.

**Comment by Youw** [comment]
Sent request.

**Comment by LudovicRousseau** [comment]
Aprouved

**Comment by LudovicRousseau** [comment]
Coverity found a new bug in `testgui/test.cpp`:
```
** CID 1019782:  Uninitialized members  (UNINIT_CTOR)
/testgui/test.cpp: 73 in MainWindow::MainWindow()()


________________________________________________________________________________________________________
*** CID 1019782:  Uninitialized members  (UNINIT_CTOR)
/testgui/test.cpp: 73 in MainWindow::MainWindow()()
67      hid_device *connected_device;
68      size_t getDataFromTextField(FXTextField *tf, char *buf, size_t len);
69      int getLengthFromTextField(FXTextField *tf);
70     
71     
72     protected:
>>>     CID 1019782:  Uninitialized members  (UNINIT_CTOR)
>>>     Non-static class member "connected_device" is not initialized in this constructor nor in any functions that it calls.
73      MainWindow() {};
74     public:
75      MainWindow(FXApp *a);
76      ~MainWindow();
77      virtual void create();
78      
```

**Comment by Youw** [comment]
Thanks for catching it.

This is just a test app, not a part of any critical implementation.
Will have a fix for it as soon as someone have a chance to get his hands to it.

**Comment by mcuee** [comment]
https://scan.coverity.com/projects/hidapi?tab=overview
Looks like there are two outstanding issues.

**Comment by Youw** [comment]
I think those are outdated.
We don't have automatic build submissions (yet). Probably a good idea to setup some.

**Comment by LudovicRousseau** [comment]
I submitted a new scan with the current source code a few hours ago.
The results are not yet available. Strange.

**Comment by LudovicRousseau** [comment]
The status is still " Last Build Status: Running. Your build is currently being analyzed ".
Maybe the server is overloaded.

**Comment by mcuee** [comment]
Indeed it seems the server is overloaded. It still shows "Last Build Status: Running. Your build is currently being analyzed".

**Comment by mcuee** [comment]
@LudovicRousseau 

Looks like the submission failed. Please help to submit a new build. Thanks.

**Comment by LudovicRousseau** [comment]
New build submitted.
The coverity results are now visible.

**Comment by Youw** [comment]
Thanks.
This time we did found some valid issues (error handling mostly).

**Comment by JoergAtGithub** [comment]
I see only Linux files listed. Were the Windows files also scanned?

**Comment by LudovicRousseau** [comment]
@JoergAtGithub I did a GNU/Linux build only. I do not use Windows.
Feel free to submit a Windows build.

**Comment by Youw** [comment]
I've prepared an on-demand Github Actions job to run and submit Coverity report for 3 platforms (Windows, Linux, macOS).
But it is not exactly usable yet: each submission overrides the previous one, so even if the job is executed - the results only for one platform will be available (whichever runs last).

Splitting into 3 different jobs for each platform is not exactly a solution, since still only one report will be available at the time, and what I want to achieve - a combiner report for all HIDAPI sources for all platforms, to track all issues alltogether on Coverity Web UI.

I'll try to get it done some time this week.

Meanwhile I've manually executed all jobs on all platforms against current master and created tickets for each issue found by Coverity.

**Comment by Youw** [comment]
Since #557 is merged, we have a single multi-platform job to submit Coverity scans for all platforms of HIDAPI. (With fixed issues I've described in my prev message.)

#558 to not forget about those checks.

That being said, I think we can safely close this ticket.
