### ISSUE TITLE
Compilation Error: Missing chid.pxd when Installing 

### ISSUE THREAD

**Issue by Mr-enthalpy** [libusb/hidapi#633]
Hello,

I've been trying to install hidapi version 0.14.0 on my system, but I'm encountering a compilation error related to a missing chid.pxd file. Here's the error output I receive:

running bdist_wheel
running build
running build_ext
FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: hid.pyx
Compiling hid.pyx because it changed.
[1/1] Cythonizing hid.pyx
building 'hid' extension
error: unknown file type '.pxd' (from 'chid.pxd')

Environment: ：

OS: [Windows 10]
Python Version: [3.12]
Steps to Reproduce:

Run pip install hidapi==0.14.0
Observe the above error during the installation process.
I've checked the repository and couldn't find the chid.pxd file. Is this a known issue or am I missing something? Any guidance or workaround would be greatly appreciated.

Thank you for your time and assistance!

**Comment by JoergAtGithub** [comment]
I guess you are reporting to the wrong project. hidapi is not written in Python.

**Comment by Youw** [comment]
Wrong project mate, we don't do python bindings for HIDAPI.
