### ISSUE TITLE
ImportError of usblib libraries

### ISSUE THREAD

**Issue by rolsman1974** [libusb/hidapi#655]
Hi,
On my Mac it is very difficult to get the hid / hidapi to work, either you get errors the usblib1 backends does not support enumeration or you get ImportErrors with regards to the usblib's

I also can find a good manual how to install these packages and to set things up correctly.
Is there a specific reason why running 'just' pip install hid , get your system ready to go?

My searches on internet didn't resolve my issue getting things to work, it did tell me lots of people facing this issue.

My request please
- just make using pip install only to set things up correctly
  or
- provide a good manual to set things up

Kind regards

Dump of the ImportError
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

**Comment by JoergAtGithub** [comment]
In this project we develop the C library hidapi - it seems you have problems with a Python wrapper, which comes from a third-party.

**Comment by JoergAtGithub** [comment]
It might be this Python wrapper, that you use: https://github.com/trezor/cython-hidapi

**Comment by mcuee** [comment]
Please raise the issue to respective project. hidapi project does not handle the Python wrapper.
