### ISSUE TITLE
Hello, does hidapi currently support iPhone 15 devices with iOS system and iPad devices with USB interface

### ISSUE THREAD

**Issue by QiaoLansheng** [libusb/hidapi#680]
Hello, does hidapi currently support iPhone 15 devices with iOS system and iPad devices with USB interface

**Comment by Youw** [comment]
There is no dedicated iOS backand for HIDAPI (I'm not sure if it is even possible).
And libusb (when libusb is used as HIDAPI backend) [doesn't support iOS either](https://github.com/libusb/libusb/wiki/FAQ#user-content-Does_libusb_support_Apple_iOS_device).

The answer is NO.
