### ISSUE TITLE
How to test it in Android with HIDAPI?

### ISSUE THREAD

**Issue by Mohanreddy1234** [libusb/hidapi#685]
I was able to test it in Linux but was unable to test it in Android Studio; please assist us with this matter.

**Comment by Youw** [comment]
This is a bug tracker, not a support forum.

So far to use HIDAPI on Android, it is only possible with HIDAPI-libusb, and HIDAPI is limited as much as libusb is limited on this matter, see: https://github.com/libusb/libusb/wiki/Android

See also: [`hid_libusb_wrap_sys_device`](https://github.com/libusb/hidapi/blob/d101e5c7e4646ecde66b650b3b8ce4904acfb13a/libusb/hidapi_libusb.h#L50C44-L50C58)
