### ISSUE TITLE
Windows: hid_write returns -1 on success

### ISSUE THREAD

**Issue by Megamouse** [libusb/hidapi#695]
On windows, hid_write returns -1 if WriteFile returns 1 (success).
function_result is only ever set to a different value if overlapped is true, which only happens if WriteFile returns 0.

This manifests in our log with `hid_write error: Success` e.g. with this pseudo-code:
```
if (hid_write(hidDevice, &report, sizeof(report)) == -1)
{
    std::cerr << "hid_write error: " << hid_error(hidDevice)) << std::endl;
}
```

**Comment by Youw** [comment]
What version of HIDAPI are you on?

**Comment by Megamouse** [comment]
0.14.0, but the relevant hid_write code didn't change on latest master either, so it should be present in the latest commit.

**Comment by Youw** [comment]
> WriteFile returns 1

I imagined this shouldn't be possible once the `lpOverlapped` is set.
Is it not the case?

**Comment by Megamouse** [comment]
Where do I check that?

**Comment by Youw** [comment]
> WriteFile returns 1 

Well, if you're saying this is what you experience, I guess there is not much we can actually check here.
I guess to fix this, we need also pass the `lpNumberOfBytesWritten` into `WriteFile`, and in case if it returns `0` (SUCCESS) use `lpNumberOfBytesWritten` as a return value of the `hid_write`.

@Megamouse will you be able to implement/test this locally in your environment?

**Comment by Megamouse** [comment]
I can try later.
In case you want to test this on your own, you need RPCS3 for windows, a DualShock3 controller and run the DualShock3 handler in the RPCS3 pad settings.
It's possible that we are doing something wrong with our implementation, but the code works, it's just that the error is logged (we only log it since the rumble/led isn't really important for running the software)

**Comment by Megamouse** [comment]
This code change seems to fix the issue.
I'm not sure why it's not running async, but the `bytes_written` is equal to `length`

![image](https://github.com/user-attachments/assets/359a6a3c-110a-48f3-a2af-66d1ad597398)

**Comment by Youw** [comment]
Fire a PR, we'll have it reviewed and additionally tested.
