### ISSUE TITLE
hidapi installation under windows / Python virtual environment 

### ISSUE THREAD

**Issue by Snolte1001** [libusb/hidapi#705]
hello,

I would like to use hidapi in a virtual Python environment under Windows 10, but the installation is not clear to me. I get the following error message

`import hid

vid = 0x16C0	# Change it for your device
pid = 0x0486	# Change it for your device

with hid.Device(vid, pid) as h:
	print(f'Device manufacturer: {h.manufacturer}')
	print(f'Product: {h.product}')
	print(f'Serial Number: {h.serial}')`

`ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll`

**Comment by Youw** [comment]
See #267
