### ISSUE TITLE
libusb backend on windows

### ISSUE THREAD

**Issue by mandar1jn** [libusb/hidapi#706]
I'm working on a program which would benefit from using the libusb backend of hidapi due to needing the ability to send control transfers. I was wondering if the libusb backend is available on windows. Libusb works on windows, but the build instructions never mention how to or if it's even possible and I had no luck getting it to compile myself.

**Comment by mcuee** [comment]
* https://github.com/libusb/hidapi/issues/319

It is not supported under Windows as of now. Please go to that issue to take a look of some of my previous mod. I will close this issue.
